# Generated by Django 3.1 on 2020-08-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20200821_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='descerption',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full time', 'full time'), ('part time', 'part time')], max_length=50),
        ),
    ]
